### ISSUE TITLE
Collecting metrics with Telegraf

### ISSUE THREAD

**Issue by levaminov** [StupidScience/qrator-exporter#1]
Some workaround with [Telegraf](https://github.com/influxdata/telegraf) without using exporter and getting deal with all upcoming API changes (for example `statistics_get` – deprecated method).

`telegraf.conf` content:

```toml
[[inputs.http]]
	name_prefix = "qrator_blocks_"
	method = "POST"
	urls = ["https://api.qrator.net/request/domain/1"]
	headers = {"X-Qrator-Auth" = "${QRATOR_API_KEY}", "Content-Type" = "application/json"}
	body = '{"method":"statistics_current_blocks"}'
	data_format = "json"
	timeout = "30s"

[[inputs.http]]
	name_prefix = "qrator_http_"
	method = "POST"
	urls = ["https://api.qrator.net/request/domain/1"]
	headers = {"X-Qrator-Auth" = "${QRATOR_API_KEY}", "Content-Type" = "application/json"}
	body = '{"method":"statistics_current_http"}'
	data_format = "json"
	timeout = "30s"

[[inputs.http]]
	name_prefix = "qrator_ip_"
	method = "POST"
	urls = ["https://api.qrator.net/request/domain/1"]
	headers = {"X-Qrator-Auth" = "${QRATOR_API_KEY}", "Content-Type" = "application/json"}
	body = '{"method":"statistics_current_ip"}'
	data_format = "json"
	timeout = "30s"

[[inputs.http]]
	name_prefix = "qrator_locations_"
	method = "POST"
	urls = ["https://api.qrator.net/request/domain/1"]
	headers = {"X-Qrator-Auth" = "${QRATOR_API_KEY}", "Content-Type" = "application/json"}
	body = '{"method":"statistics_current_locations"}'
	data_format = "json"
	timeout = "30s"

[[outputs.prometheus_client]]
	listen = ":9273"
```

`QRATOR_API_KEY` environment variable than contains valid API-token (https://client.qrator.net/qrator/apitoken/).
